### PR TITLE
Add Ice framework 1.0

### PR DESCRIPTION
**Pull request by mruz**
[ice/framework](https://github.com/ice/framework)

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you. I'm going to look into it.

**Comment by kenjis** [comment]
I'm sorry, my benchmarking environment is CentOS 6.

~~~
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
~~~

The gcc has no LTO option, so I removed it.

~~~
diff --git a/ext/install b/ext/install
index 817608c..070bfbf 100755
--- a/ext/install
+++ b/ext/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 export CC="gcc"
-export CFLAGS="-O2 -Wall -fvisibility=hidden -flto -DZEPHIR_RELEASE=1"
+export CFLAGS="-O2 -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"
 if [ -f Makefile ]; then
        sudo make --silent clean
        sudo phpize --silent --clean
~~~

**Comment by kenjis** [comment]
I updated my benchmarks:
https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

**Comment by mruz** [comment]
Thanks, good score on the ice ;)

**Pull request merged**
