### PR TITLE
Add number of included files

### PR DESCRIPTION
**Pull request by mruz**

### CODE REVIEW

**Comment by mruz** [comment]
What do you think about this changes?
benchmark

**Comment by kenjis** [comment]
It is interesting, but I can't accept the changes. Because I have more than 20 frameworks.
The graph would be too large.

By the way, why your Phalcon and Ice are so faster than other PHP implemented frameworks?

**Comment by mruz** [comment]
I don't know, maybe multithreading? I run the benchmark on real machine:
CPU: i7-4702MQ 4 cores 8 threads
RAM: 12 GB
Nginx: 1.8.0
PHP-FPM: 5.6.14

Results for Phalcon and Ice are very similar, sometimes Phalcon is a bit better.

**Comment by kenjis** [comment]
Thank you for your info! Very interesting.

**Comment by kenjis** [comment]
I cherry-picked your commits, and added simple theme functionality for graph output.

`http://localhost/php-framework-benchmark/?theme=mruz`

**Comment by motin** [comment]
If the changes are cherry-picked, maybe this PR can be closed?

**Comment by mruz** [comment]
How about the commits:
> Output, add number of included files https://github.com/mruz/php-framework-benchmark/commit/b639da1656602108785919d99b4062e8faa05229
Output, add greater accuracy to relative https://github.com/mruz/php-framework-benchmark/commit/fbc74c33c927fe268124aae21e47f462734ddff1

**Pull request closed without merging**
