### PR TITLE
Use .gitignore

### PR DESCRIPTION
**Pull request by mruz**
Ignore everything except `.gitignore` file in the `/cache`, `/log` folders:
```
*
!.gitignore
```

### CODE REVIEW

**Comment by kenjis** [comment]
Why do I need this?

**Comment by mruz** [comment]
It's improvements. If you run benchmark it generates local files cache, logs, output, etc. This will skip them in the next commit.

**Comment by kenjis** [comment]
I ran benchmark, but the status is like below:

~~~
[vagrant@localhost php-framework-benchmark]$ git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   output/results.hello_world.log
#
no changes added to commit (use "git add" and/or "git commit -a")
~~~

**Comment by mruz** [comment]
.gitignore is only meant to prevent files from being tracked. Once a file is tracked (`results.hello_world.log`), the ignore file has no effect on it.

You can make Git ignore changes to your file using 
```
git update-index --assume-unchanged output/results.hello_world.log
```

Or remove this log (it's changing always on local) and commit.

**Comment by kenjis** [comment]
I wanted to say that the status is okay already.

My question is why do I need so many changes?
I have no problem now. I don't get what is improved.

`output/results.hello_world.log` should be committed. It is needed to output the benchmark graph.
If you git clone this repository, you can see the graph. So the `modified` state is okay to me.

**Comment by mruz** [comment]
OK, I reverted removing.
Because after I run the benchmark locally I have unadded changes, eg
```
phalcon-2.0/app/cache/_home_mruz_dropbox_git_ice_benchmark_phalcon-2.0_app_views_index_index.volt.php
phalcon-2.0/app/cache/_home_mruz_dropbox_git_ice_benchmark_phalcon-2.0_app_views_index.volt.php
```
`phalcon-2.0/app/cache/.gitkeep` is only used for keeping empty cache directory during clone, so you also need to add to the .gitignore:
```
cache/*
```

Maybe it's not big deal ;)

**Comment by kenjis** [comment]
Added: https://github.com/kenjis/php-framework-benchmark/commit/cfde1be57d3eeb8011d6a73d4846df88bebd691f
Thank you for you report.

**Pull request closed without merging**
