### PR TITLE
Added CleverStyle Framework 5.4

### PR DESCRIPTION
**Pull request by nazar-pc**

### CODE REVIEW

**Comment by kenjis** [comment]
@nazar-pc Thank you for your PR.
Does it work on PHP 5.5?

**Comment by nazar-pc** [comment]
No, 5.6 is needed

**Comment by nazar-pc** [comment]
Is 5.6 requirement a blocker here?

**Comment by kenjis** [comment]
No. I will merge this PR later.
Actually I have to update my benchmarking environment to PHP 5.6.

**Comment by kenjis** [comment]
@nazar-pc 

This PR does not work on my environment. So I will revert.

```
***** cleverstyle-5.4 *****
PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, near ",": syntax error in phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/202 on line 53
PHP Stack trace:
PHP   1. {main}() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php:0
PHP   2. include() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php:9
PHP   3. cs\Installer::install() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/cli.php:196
PHP   4. cs\Installer::initialize_db_structure() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/Installer.php:110
PHP   5. cs\DB\SQLite->q() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/Installer.php:253
PHP   6. cs\DB\_Abstract->q() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/202:42
PHP   7. cs\DB\_Abstract->execute_multiple() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/203:107
PHP   8. cs\DB\SQLite->q_multi_internal() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/203:154
PHP   9. cs\DB\SQLite->q_internal() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/202:61
PHP  10. SQLite3->query() phar:///home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/installer.phar.php/fs/202:53
Can't import system tables structure for selected database engine! Installation aborted.PHP Notice:  Undefined index: name in /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/functions.php on line 314
PHP Stack trace:
PHP   1. {main}() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/cli:0
PHP   2. require_once() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/cli:27
PHP   3. cs\Page::instance() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/index.php:41
PHP   4. cs\Page::instance_prototype() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:33
PHP   5. cs\Page::instance_prototype_state_init() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:74
PHP   6. cs\Page->init() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:123
PHP   7. cs\Page->init_config() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/classes/Page.php:177
PHP   8. get_core_ml_text() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/classes/Page.php:193
PHP Notice:  Undefined index: theme in /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/classes/Page.php on line 194
PHP Stack trace:
PHP   1. {main}() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/cli:0
PHP   2. require_once() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/cli:27
PHP   3. cs\Page::instance() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/index.php:41
PHP   4. cs\Page::instance_prototype() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:33
PHP   5. cs\Page::instance_prototype_state_init() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:74
PHP   6. cs\Page->init() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/traits/Singleton/Base.php:123
PHP   7. cs\Page->init_config() /home/vagrant/public/php-framework-benchmark/cleverstyle-5.4/core/classes/Page.php:177
<!doctype html>
<title>500 Internal Server Error</title>
```

**Comment by nazar-pc** [comment]
Which version of SQLite 3 do you have there? SQLite 3.7.11 is needed for complete operation, but even a bit older should be fine for installation.
How can I test your environment?

**Comment by kenjis** [comment]
I have 3.6.
~~~
$ rpm -qa | grep sqlite
sqlite-devel-3.6.20-1.el6_7.2.x86_64
sqlite-3.6.20-1.el6_7.2.x86_64
~~~

My benchmark environment is CentOS 6 VM.
You can get it from <https://github.com/kenjis/vagrant-centos6-php>.

**Comment by nazar-pc** [comment]
Well, CentOS 6 is sooo old.
3.6.20 was released 2009-11-04 according to official info: https://www.sqlite.org/changes.html#version_3_6_20

Can you update it to something above 3.7.11? I'm not CentOS user, but looks like there are some repositories, also in VM you can just compile upstream version from sources.

**Comment by kenjis** [comment]
Yeah, I know it's old.

By the way, why do you need SQLite to install?
It is the first framework which depends on SQLite.

**Comment by nazar-pc** [comment]
This is because it is a bit different in its construction.
It is not split into components like many popular frameworks are and uses database for storing non-critical configuration. While DB is not used during benchmarking, it is needed for initial setup and initial cache population during first request.
I can add pre-installed system, but it would be pretty ugly and more difficult to maintain.

**Pull request merged**
