### PR TITLE
Zend Framework 3.0 (WIP)

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Comment by seyfer** [comment]
Please update results with zf-3.0

**Comment by kenjis** [comment]
```
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|zf-2.5             |              58.21|     1.0|       2.96|     1.5|
|zf-3.0             |             154.53|     2.7|       1.93|     1.0|
```

**Comment by kenjis** [comment]
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|zf-1.12            |             289.19|     4.7|       1.27|     1.0|
|zf-2.5             |              61.77|     1.0|       2.96|     2.3|
|zf-3.0             |             165.33|     2.7|       1.93|     1.5|
|laravel-5.3        |              98.51|     1.6|       2.51|     2.0|

**Comment by seyfer** [comment]
Please update README on main page with new added zf3 and zf1.

**Comment by kenjis** [comment]
I want to update the benchmarks on README, but I must add latest some major frameworks before it.
And I don't add zf1 on README.

**Comment by cebe** [comment]
@kenjis when you make a new benchmark for the readme, make sure to sort the frameworks in the graph, it's a bit odd that it goes up a bit in the middle and then down again. https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

**Pull request merged**
