### PR TITLE
Added Cygnite PHP Framework v1.3.1

### PR DESCRIPTION
**Pull request by sanjoydesk**
Added Cygnite PHP Framework v1.3.1 For Benchmark

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you. I'm going to look into it.

**Comment by sanjoydesk** [comment]
Thank you very much @kenjis

**Comment by kenjis** [comment]
I updated my benchmarks:
https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

**Comment by sanjoydesk** [comment]
Good to see the result. It seems [Cygnite PHP Framework!](http://www.cygniteframework.com/) does better in terms of performance compare to most of the frameworks. Hope we can well optimize it, to see much better results.

I feel like lumen, silex, Ice, slim etc. should be in different table as all are micro framework. So would like to suggest if we separate full stack and micro frameworks benchmark results than would be nice to compare.

Thank You for the update. @kenjis :+1:

**Pull request merged**
