### PR TITLE
Added Tipsy 0.10

### PR DESCRIPTION
**Pull request by arzynik**
https://github.com/arzynik/Tipsy

### CODE REVIEW

**Comment by kenjis** [comment]
@arzynik Thank you!

Would you please add info in README <https://github.com/kenjis/php-framework-benchmark#reference> ?

**Comment by arzynik** [comment]
@kenjis added to reference

**Comment by kenjis** [comment]
I've just added the result: https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

Congratulations! Tipsy is faster than FatFee.

**Comment by arzynik** [comment]
wow!

**Pull request merged**
