### PR TITLE
Improved the Symfony application configuration

### PR DESCRIPTION
**Pull request by javiereguiluz**
@kenjis thanks for creating this benchmark of PHP frameworks and thanks for including Symfony in it.

I was checking the configuration of the tested Symfony application and I realized that it's not correct. The problem is that right now Symfony is loading a lot of things that are unneeded for the benchmark (database access, logs, emails, etc.)

I propose you the changes included in this pull request to disable anything that Symfony doesn't need to run the test. I'd be great if you could accept this pull request and re-run the benchmark tests. If you have any question about these changes, please ask me. Thanks!

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for your PR.

I respect Symfony, but I don't know it well, so I appreciate your advice. I have some questions.

First of all, I applied your patch in my current benchmark environment. And I got the results below:

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|cake-3.0           |             266.66|     3.6|       1.00|     2.0|
|symfony-2.6        |             259.30|     3.5|       1.00|     2.0|

Now Symfony is as fast as Cake.

By the way, my goal is not to build fastest Hello World application. I added the goal in README. Would you mind seeing https://github.com/kenjis/php-framework-benchmark#php-framework-benchmark ?

I would like to merge some parts of this PR, but not all. Because I think removing all comment lines is going too far. I did not do like that, and will not do also.

I’m going to remove unused bundles.

I use route annotation, because *Symfony Best Practices* do so. http://symfony.com/doc/current/best_practices/controllers.html
But you changed it. Do you recommend not to use route annotation to Symfony users?

**Comment by javiereguiluz** [comment]
@kenjis thanks for your kind response. Let me answer your questions:

**1) Using annotations for routes**: indee the best practices recommend that. When we develop a Symfony application to explain how to use Symfony (e.g. https://github.com/symfony/symfony-demo) we always use annotations.

However, Symfony suppors both the (fast) configuration file based routes and the fancy (but a bit slower) annotaitons based routes. Since the rest of the frameworks use a configuration file for the benchmark, I find it unfair to not use it in Symfony benchmark.

**2) Removing AcmeDemoBundle contents**: the AcmeDemoBundle was a demonstration bundle used to learn Symfony. Recently we decided to remove it for ever and never use it again. That's why we developed a separate application to learn Symfony: https://github.com/symfony/symfony-demo. For that reason, I think it's reasonable to remove anything related to the AcmeDemoBundle.

**3) Removal of configuration options**: in Symfony, when you put an option like `form` or `assetic` in the `config.yml` file, Symfony automatically loads that feature in the application. As you say in the README of this repository, it would be absurd to load things like an ORM for this benchmark. I also find it unfair to load things like form and validation, email sender, CSS and JS files manipulator, etc. That's why I commented those options, because that's the way to not load those features.

In any case, this was just a humble proposal. You are in charge of the benchmark and you have to make the decission of what changes to accept. However, if you prefer not to optimize Symfony in this way, could it be possible to add a small note in the benchmark saying that Symfony it's not optimized and it's just the regular Symfony Standard Edition code and configuration? Thanks!

**Comment by kenjis** [comment]
@javiereguiluz Thank you for your answer and detailed explanation. I appreciate that you stated your logical opinions.

This is my benchmark, I made it because I want to know. But every benchmarking is based on a lot of conditions. I try to make this benchmarking fair, but I could not say it is perfectly fair. There must be points which I miss.

**1) Using annotations for routes** I agree with you. Other frameworks do not use annotation for routing.

**2) Removing AcmeDemoBundle contents** I have a question. It seems AcmeDemoBundle is not used at all in this Symfony application. Removing them affects performance? Why?

**3) Removal of configuration options** I got it. I must comment out not to load unused features.

>  I think removing all comment lines is going too far. I did not do like that, and will not do also.

It means comments in source code. Eg, https://github.com/kenjis/php-framework-benchmark/pull/3/files#diff-aeeea3ae1b8361ac1f8f9263dcd4ef04L8

**Comment by javiereguiluz** [comment]
Thanks for your reply. It's great that you are so open to other people's opinions!!

Regarding the AcmeDemoBundle, it's true that you can leave its source code without affecting the benchmark. It's only necessary to remove its routes from `app/config/routing_dev.yml` and remove its bundle from the `app/AppKernel.php` file.

Regarding the comments of `web/app.php` you are right and you can leave them without affecting the bechmark. I probably went too far with my obsession of cleaning unneeded things. Sorry for that!

**Comment by kenjis** [comment]
Thank you for your answers.

I pushed my change. Probably, it is almost the same as yours.

https://github.com/kenjis/php-framework-benchmark/compare/ad314e1ec0480567035d07684fb0474eee6e862d...0bac124d61dc93fa126a9b88aeef62843c5a0edc

I commented out params. I believe it is no impact for the results.

The results are more or less the same as your patch:

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|cake-3.0           |             256.58|     3.3|       1.00|     2.0|
|symfony-2.6        |             269.91|     3.5|       1.00|     2.0|

**Comment by javiereguiluz** [comment]
:+1: awesome! Your changes look great to me. Thanks for being so responsive!

**Comment by kenjis** [comment]
I've updated my blog article. All done.
Thanks for your kind feedback!

**Comment by javiereguiluz** [comment]
Thankn you @kenjis.

**Comment by kenjis** [comment]
I changed my benchmarking policy: #10
So I reverted symfony's optimization code.

But I created a new branch `optimize`, and apllied your changes.

If I did something wrong or missing, please inform me.

**Comment by javiereguiluz** [comment]
@kenjis I have a quick question: can we perform extreme optimizations in that `optimize` branch? Of course I'm not talking about doing stupid things such as using `echo "Hello World"` in the front controller, but tweaking Symfony to the extreme to improve its performance to the limit.

And now I have another suggestion: could you show the comparison before "out-of-the-box" and "optimized" benchmarks? That way people could realize how fast their framework really is if they optimize it properly.

**Comment by kenjis** [comment]
@javiereguiluz I don't know, but if you think it is *extreme*, I maybe do not accept it. I'm not interested in building fastest hello world application.

I added https://github.com/kenjis/php-framework-benchmark/tree/optimize#comparision-before-and-after-optimization

**Pull request closed without merging**
