### PR TITLE
Zend Framework 2.4 basic optimization

### PR DESCRIPTION
**Pull request by jorelcb**
Based on:
http://blog.hock.in/2014/05/14/maximising-performance-in-zf2-phpuk/
http://www.masterzendframework.com/performance-2/classmap-autoloader
http://hounddog.github.io/blog/performance-in-zend-framework-2/

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you for your PR.

Your code did not work (Parse error and Fatal error), so I fixed: https://github.com/kenjis/php-framework-benchmark/commit/f013d2e14bc22a0b23c5c9c94ed8154c86e07403
Is it okay?

**Comment by jorelcb** [comment]
Perfect!. Thank You and sorry about the mistake.

**Comment by jorelcb** [comment]
getAutoloaderConfig function fixed, please check!

**Comment by kenjis** [comment]
Thank you. But I already fixed and merged your PR.

I updated my benchmarks:
https://github.com/kenjis/php-framework-benchmark/tree/optimize#hello-world-benchmark

But I don't see the effect of this optimization. In fact the rps decreased a little by chance.
When I benchmarked for the first time, the number increased a little.

**Pull request closed without merging**
