### PR TITLE
Added zf-1.12

### PR DESCRIPTION
**Pull request by seyfer**

### CODE REVIEW

**Comment by axot** [comment]
```bash
$ bash setup.sh zf-1.12/
***** zf-1.12 *****
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Creating project at /var/www/php-framework-benchmark/zf-1.12/helloworld
Note: This command created a web project, for more information setting up your VHOST, please see docs/README

Warning: main(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/php-framework-benchmark/zf-1.12/library/Zend/Test/PHPUnit/ControllerTestCase.php on line 48

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/php-framework-benchmark/zf-1.12/library/Zend/Test/PHPUnit/ControllerTestCase.php on line 48
rm: cannot remove ‘./zf-1.12/helloworld/public/.htaccess’: Permission denied
```
@seyfer how to resolve this?

**Comment by seyfer** [comment]
@axot, I will try to reproduce the error and resolve it.

**Comment by seyfer** [comment]
@kenjis @axot please check it now

**Comment by axot** [comment]
@seyfer almost work!
```
[kuma@shao-test-app php-framework-benchmark]$ bash setup.sh zf-1.12/
***** zf-1.12 *****
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing zendframework/zendframework1 (1.12.20)
    Downloading: 100%

Generating optimized autoload files
rm: cannot remove ‘./zf-1.12/helloworld/public/.htaccess’: Permission denied
```
Is this a permission issue?

**Comment by kenjis** [comment]
It seems there is no Hello controller.
And you must add the below line in the end of `index.php`:
```php
require $_SERVER['DOCUMENT_ROOT'].'/php-framework-benchmark/libs/output_data.php';
```

**Comment by axot** [comment]
@kenjis After add out_data.php it works now. Thank you.

```bash
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|phalcon-2.0        |          14,780.93|     0.0|       0.00|     0.0|
|kumbia-1.0-dev     |           4,990.31|     0.0|       0.29|     0.0|
|tipsy-0.10         |           2,400.61|     0.0|       0.33|     0.0|
|fatfree-3.5        |           6,260.43|     0.0|       0.42|     0.0|
|ci-3.0             |           4,123.33|     0.0|       0.43|     0.0|
|nofuss-1.2         |           3,586.36|     0.0|       0.40|     0.0|
|bear-1.0           |          12,032.88|     0.0|       0.00|     0.0|
|lumen-5.1          |           3,320.62|     0.0|       0.71|     0.0|
|yii-2.0            |          12,820.21|     0.0|       0.00|     0.0|
|silex-1.3          |           2,287.06|     0.0|       0.76|     0.0|
|cygnite-1.3        |           2,415.39|     0.0|       0.70|     0.0|
|fuel-1.8           |           1,948.56|     0.0|       0.00|     0.0|
|symfony-2.7        |             553.84|     0.0|       2.85|     0.0|
|symfony-3.0        |             737.97|     0.0|       3.14|     0.0|
|laravel-4.2        |          12,263.65|    21.3|       0.00|     0.0|
|laravel-5.0        |          12,094.89|    21.0|       0.00|     0.0|
|laravel-5.1        |          10,435.66|    18.1|       0.00|     0.0|
|laravel-5.2        |             575.52|     1.0|       2.38|     0.0|
|zf-2.5             |             615.57|     0.0|       2.64|     0.0|
|zf-1.12            |           1,949.75|     1.0|       1.27|     1.0|
```

**Comment by kenjis** [comment]
`http://127.0.0.1/php-framework-benchmark/zf-1.12/public/` is not good URL.
All other frameworks specify the Hello controller.
Please change the URL like `http://127.0.0.1/php-framework-benchmark/zf-1.12/public/index.php/application/hello/index`

**Comment by seyfer** [comment]
`http://127.0.0.1/php-framework-benchmark/zf-1.12/public/index.php/application/hello/index`

I don't know how to do it. Passing parameters through index.php doesn't work for me with zf-3 and with zf-1 too. Even with right routing config. 
But it works when project is separated in own vhost.

**Comment by seyfer** [comment]
Why I can't output Hello World! in default index controller?
I did it and @axot even got results.

I did the same for zf-3.

**Comment by seyfer** [comment]
@kenjis 
please show your nginx default vhost config. maybe it's something wrong with mine.
i will try to fix it with right config then

**Comment by kenjis** [comment]
@seyfer I use Apache.

**Comment by kenjis** [comment]
@seyfer @axot 

I fixed a bit this PR and merge into master branch.

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|zf-1.12            |             284.31|     4.7|       1.27|     1.0|
|zf-2.5             |              61.13|     1.0|       2.96|     2.3|
|zf-3.0             |             163.44|     2.7|       1.93|     1.5|
|laravel-5.2        |             115.80|     1.9|       2.40|     1.9|

**Comment by kenjis** [comment]
@seyfer @axot If there is something wrong with zf1 in master branch, feel free to send another PR.

**Comment by seyfer** [comment]
@kenjis , thank you.

**Pull request closed without merging**
