### PR TITLE
added our framework to the benchmarks

### PR DESCRIPTION
**Pull request by jarnix**
Hello, I hope I did not forget anything, the results are okay so I thought I could add our framework to the bench. gj on this benchmark :)

### CODE REVIEW

**Comment by kenjis** [comment]
I got the error. Is it okay?

~~~
$ php html/index.php -m compress
Error
exception: scandir(.../php-framework-benchmark/nofussframework-1.2.3/vendor/nofussframework/nofussframework/Nf/php/classes/Nf): failed to open dir: No such file or directory
~~~

**Comment by jarnix** [comment]
Hello Kenjis,

I reproduced the issue, it seems that you might just have to launch a "composer install" :) Am I right ?

**Comment by jarnix** [comment]
Hello Kenjis,

I reproduced the issue. It seems that you might just have to launch a "composer install" :) Am I right ?

**Comment by kenjis** [comment]
Do you tell me to remove the line? It seems okay.

By the way, how do I configure a specific route?
I changed `routes/php-framework-benchmark.php` like below, I can't access the page.

~~~
<?php

return array(
    array('regexp' => 'hello/index', 'controller' => 'home/index/index')
);
~~~

And the why is the routing file name `routes/php-framework-benchmark.php`? Do you configure the name somewhere?

**Comment by kenjis** [comment]
To merge this PR, would you please fix the following?

* The folder name should be the format like `framework-name-X.Y` (in this case `nofussframework-1.2`)
* Set the route for `hello/index`
* Don't comment out other frameworks in `list.sh`
* The Hello controller outputs `Hello World!`
* The `setup.sh` does not cause errors

**Comment by jarnix** [comment]
Hello :)

- the folder name is now in the correct format
- I added the route for hello/index
- other frameworks were commented by mistake, however I noticed that in the HEAD branch you have commented others so you might need to double check (fuel, noframework)
- the hello controller now output the correct hello world :)
- I failed to reproduce any errors in the setup.sh. I suppose that there were files that were not necessary.

The route file is called "routes/php-framework-benchmark.php" because of the root folder of the benchmark, the framework is designed to run at the root directory so I had to use this trick but it's nothing special really.

To answer your other question ;) the line in _benchmark/setup.sh :
```php html/index.php -m compress```
is necessary. It launched okay on my virtual machine.

I hope it's fine this time :)

**Comment by kenjis** [comment]
Thank you!

I fixed the route: https://github.com/kenjis/php-framework-benchmark/commit/77515fd143c130448d58ef17585109e3f9b8f5eb

**Comment by kenjis** [comment]
nofussframework is faster than slim3.

Unofficial resutls:

~~~
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|phalcon-2.0        |           1,379.91|    38.4|       0.50|     1.0|
|ice-1.0            |           1,118.21|    31.1|       0.50|     1.0|
|slim-2.6           |             758.93|    21.1|       0.50|     1.0|
|codeigniter-3.0    |             672.09|    18.7|       0.50|     1.0|
|nofussframework-1.2|             544.46|    15.1|       0.50|     1.0|
|slim-3.0           |             490.84|    13.7|       0.75|     1.5|
|bear-1.0           |             424.94|    11.8|       1.00|     2.0|
~~~

**Comment by kenjis** [comment]
The route was wrong. Fixed: https://github.com/kenjis/php-framework-benchmark/commit/a1042833b915f5410f0c0065fd681f1a221b8edf

**Comment by kenjis** [comment]
I've update benchmark resutls: https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

**Pull request merged**
