### PR TITLE
Added zf-3.0

### PR DESCRIPTION
**Pull request by seyfer**

### CODE REVIEW

**Comment by kenjis** [comment]
I can't merge this PR, because it does not have [HelloController.php](https://github.com/kenjis/php-framework-benchmark/blob/master/zf-2.5/module/Application/src/Application/Controller/HelloController.php).

**Comment by kenjis** [comment]
And please add this:
```diff
--- a/zf-3.0/public/index.php
+++ b/zf-3.0/public/index.php
@@ -38,3 +38,5 @@ if (file_exists(__DIR__ . '/../config/development.config.php')) {
 
 // Run the application!
 Application::init($appConfig)->run();
+
+require $_SERVER['DOCUMENT_ROOT'].'/php-framework-benchmark/libs/output_data.php';
```

**Comment by seyfer** [comment]
@kenjis, ok I will add controller and suggested code line.

**Comment by seyfer** [comment]
@kenjis , please look at my recent fixes.

**Comment by kenjis** [comment]
Why your URL is `http://127.0.0.1/php-framework-benchmark/zf-3.0/public/`?
It should be like `http://127.0.0.1/php-framework-benchmark/zf-3.0/public/index.php/application/hello/index`. Not default controller, but specific controller.

**Comment by seyfer** [comment]
I have commented the reason in hello_world.sh.
Passing route params through  index.php doesn't work in v3. 

You can try, but I'm not sure if `http://127.0.0.1/php-framework-benchmark/zf-3.0/public/application/hello/index` will work.
It's worked when I have created host `http://zf3.loc`
and url `http://zf3.loc/application/hello/index` worked. Because index.php configured in vhost.

**Comment by kenjis** [comment]
@seyfer I made another PR for ZF3: #71 
But I must set `development-enable`. I don't know why. See https://github.com/kenjis/php-framework-benchmark/pull/71/commits/1273d9d0abbde905e96a14197320dd622855e2c6

Do you know anything?

**Comment by seyfer** [comment]
You should clear `data/cache/`
And it's was my mistake to, I forgot to do it. It's because old config stored in `data/cache/` directory.

Just try to add `rm data/cache/*` at the end of the setup script.

**Comment by kenjis** [comment]
@seyfer Thanks! It worked.

**Comment by kenjis** [comment]
#71 was merged. So I close this PR.
Thank you for your cooperation.

**Comment by kenjis** [comment]
@seyfer 

I updated my benchmarks: https://github.com/kenjis/php-framework-benchmark#hello-world-benchmark

Thank you!

**Pull request closed without merging**
